name       : gstreamer-1.0-plugins-good
version    : 1.8.2
release    : 13
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.8.2.tar.xz : 8d7549118a3b7a009ece6bb38a05b66709c551d32d2adfd89eded4d1d7a23944
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : Plugins deemed to be of good quality
description: |
    Plugins that the GStreamer developers believe to be of good quality and licensing
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(flac)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libv4l2)
    - pkgconfig(orc-0.4)
    - pkgconfig(shout)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vpx)
    - pkgconfig(wavpack)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - wavpack-utils
    - libjpeg-turbo-devel
    - aalib-devel
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Good Plugins 1.6.1 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
