name       : gstreamer-1.0-plugins-good
version    : 1.12.3
release    : 16
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.12.3.tar.xz : 13e7f479296891fef5a686438f20ba7d534680becf2269ecc5ee24aa83b45f03
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : Plugins deemed to be of good quality
description: |
    GStreamer is a streaming media framework, based on graphs of elements which
    operate on media data.
    
    GStreamer Good Plugins is a collection of well-supported plugins of
    good quality and under the LGPL license.
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(flac)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libv4l2)
    - pkgconfig(orc-0.4)
    - pkgconfig(shout)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vpx)
    - pkgconfig(wavpack)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - aalib-devel
    - bzip2-devel
    - libjpeg-turbo-devel
    - wavpack-utils
setup      : |
    %patch -p1 < $pkgfiles/0001-tests-souphttpsrc-Update-test-cert.pem.patch
    %patch -p1 < $pkgfiles/0002-tests-souphttpsrc-Make-ssl_cert-key_file-static.patch
    %patch -p1 < $pkgfiles/0003-tests-souphttpsrc-Avoid-deprecated-server-ssl-proper.patch
    %patch -p1 < $pkgfiles/0004-tests-souphttpsrc-Avoid-deprecated-ssl-ca-file-prope.patch

    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Good Plugins ${version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
