name        : gstreamer-1.0-plugins-good
version     : 1.6.1
release     : 6
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.6.1.tar.xz : 86d4b814099f7b7b16be19d4b94fa41002ac01fdf1525b07c5764d54c0605935
license     :
    - LGPL-2.1
summary     : Plugins deemed to be of good quality
builddeps   :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(xfixes)
    - pkgconfig(xdamage)
    - pkgconfig(cairo-gobject)
    - pkgconfig(flac)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libdv)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libiec61883)
    - pkgconfig(shout)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vpx)
    - pkgconfig(wavpack)
    - pkgconfig(orc-0.4)
    - wavpack-utils
    - libjpeg-turbo-devel
    - aalib-devel
description : |
    Plugins that the GStreamer developers believe to be of good quality and licensing
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Good Plugins 1.6.1 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
