name       : gstreamer-1.0-plugins-good
version    : 1.12.4
release    : 18
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.12.4.tar.xz : 649f49bec60892d47ee6731b92266974c723554da1c6649f21296097715eb957
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : Plugins deemed to be of good quality
description: |
    GStreamer is a streaming media framework, based on graphs of elements which
    operate on media data.

    GStreamer Good Plugins is a collection of well-supported plugins of
    good quality and under the LGPL license.
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(flac)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libv4l2)
    - pkgconfig(orc-0.4)
    - pkgconfig(shout)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vpx)
    - pkgconfig(wavpack)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - aalib-devel
    - bzip2-devel
    - wavpack-utils
setup      : |
    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Good Plugins ${version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
