name       : gstreamer-1.0-plugins-good
version    : 1.16.2
release    : 34
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.16.2.tar.xz : 40bb3bafda25c0b739c8fc36e48380fccf61c4d3f83747e97ac3f9b0171b1319
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Plugins deemed to be of good quality
description: |
    GStreamer is a streaming media framework, based on graphs of elements which
    operate on media data.

    GStreamer Good Plugins is a collection of well-supported plugins of
    good quality and under the LGPL license.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(flac)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - pkgconfig(libmpg123)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(orc-0.4)
    - pkgconfig(shout)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(twolame)
    - pkgconfig(vpx)
    - pkgconfig(wavpack)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - aalib-devel
    - bzip2-devel
    - lame-devel
    - wavpack-utils
setup      : |
    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Good Plugins ${version} Solus" \
               --with-package-origin="https://getsol.us"
build      : |
    %make
install    : |
    %make_install
